language: python
python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'

install:
  - pip install wheel
  - pip install twine
  - python setup.py bdist_wheel

script:
  - twine upload -u USER -p PASSWORD dist/*
